# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-27 04:34
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ("-pub_date",)},
        )
    ]
